Recreate pyproject with uv + VSCode workspace
I was having issues installing microtorch as a dependency because of the
following error:

```
uv add --editable ../
Resolved 3 packages in 8ms
  × Failed to build `microtorch @ file:///home/rafid_cohere_com/Workspace/microtorch`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_editable` failed (exit status: 1)

      [stderr]
      error: Multiple top-level packages discovered in a flat-layout: ['mten', 'microtorch', 'coverage_html'].

      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.

      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:

      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names

      To find more information, look for "package discovery" on setuptools docs.

      hint: This usually indicates a problem with the package or the build environment.
  help: `microtorch` was included because `microtorch-examples` (v0.1.0) depends on `microtorch`
```

To solve this issue, I recreated the pyproject using this command:

```
uv init --name microtorch --package --description "<desc>" ./
```

I also created a VScode workspace file that includes both "microtorch"
and the "examples" project